name: Cypress Tests
on: [push, pull_request]

jobs:
  prettier-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qa-e2e
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: qa-e2e/package-lock.json
      - run: npm ci
      - run: npx prettier --check .

  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qa-e2e
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: qa-e2e/package-lock.json
      - run: npm ci
      - uses: cypress-io/github-action@v6
        with:
          working-directory: qa-e2e
          install: false
